//go:build ignore

// Command generate writes version_gen.go with the current `git describe` value.
// Run via `go generate ./internal/buildinfo`; commit the result. The release
// workflow regenerates it from the exact tag before building.
package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

const target = "version_gen.go"

func main() {
	version := gitDescribe()
	if version == "" {
		version = "devel"
	}

	src := fmt.Sprintf(`// Code generated by generate.go; DO NOT EDIT.

package buildinfo

func init() { version = %q }
`, version)

	if err := os.WriteFile(target, []byte(src), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%s)\n", target, version)
}

func gitDescribe() string {
	out, err := exec.Command("git", "describe", "--tags", "--always", "--dirty").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
